venv:
	python -m venv ENV

requirements: venv
	. ENV/bin/activate && \
	$(which pip) install -U -r requirements.txt && \
	$(which pip3) install -U -r requirements.txt

test: requirements
	. ENV/bin/activate && python -m pyright src
