venv:
	python -m venv ENV

requirements: venv
	. ENV/bin/activate && \
	$(which pip) install -r requirements.txt && \
	$(which pip3) install -r requirements.txt

test: requirements
	. ENV/bin/activate && pyright src
