[package]
name = "nostr-relay-pool"
version = "0.29.2"
edition = "2021"
description = "Nostr Relay Pool"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "relay", "pool"]

[features]
default = []
nip11 = ["nostr/nip11"]

[dependencies]
async-utility.workspace = true
async-wsocket = "0.3"
atomic-destructor = { version = "0.1", default-features = false, features = ["tracing"] }
nostr = { workspace = true, features = ["std"] }
nostr-database.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true, features = ["std", "attributes"] }
